"""init_4

Revision ID: 764d0bed46c6
Revises: 673f3587a97f
Create Date: 2025-10-12 14:34:50.301860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d0bed46c6'
down_revision: Union[str, Sequence[str], None] = '673f3587a97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('trip_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'trips', ['trip_id'], ['id'])
    op.alter_column('trips', 'organizer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'organizer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'trip_id')
    # ### end Alembic commands ###
