"""iniasdasds

Revision ID: be419783ae2b
Revises: 0043bb24d961
Create Date: 2025-10-23 22:46:10.543926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be419783ae2b'
down_revision: Union[str, Sequence[str], None] = '0043bb24d961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('users_yandex_id_key'), 'users', type_='unique')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_yandex_id_key'), 'users', ['yandex_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
